[directories]
model_run = "X:/Projects/CHAMP7CE/Run3_2023"
resources = "Q:/Model Development/Simwrapper Validation/resources"
transit_input_dir = "Q:/Data/Observed/Validation/2023"
control_file = "Q:/Model Development/Simwrapper Validation/notebooks/transit/script/transit.ctl"
markdown_output_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/table"
MUNI_output_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/val_MUNI"
BART_output_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/val_BART"
Screenline_output_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/val_Screenline"
total_output_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/val_Total"
Base_model_dir = "X:/Projects/DTX/CaltrainValidation/s8_2019_Base"
SHP_file_dir = "X:/Projects/Miscellaneous/validation_simwrapper/test/shp"
necessary_scripts_for_vmt_folder = "Y:/Users/Patricie/champ/champ/scripts/summarize"

# Input
[transit]
line_rename_filename = "transit_line_rename.csv"
transit_validation_2019_alfaro_filepath = "Q:/Model Development/CHAMP7/Validation_2023/TransitValidation/Observed/Transit_Validation_2019 - MA.xlsx"
FREEFLOW_SHP = "FREEFLOW_nodes.shp"
observed_BART = "observed_bart_station.csv"
observed_BART_county = "observed_bart_county.csv"
observed_BART_Screenline = "observed_bart_screenline.csv"
observed_MUNI_Line = "observed_muni_line.csv"
observed_Screenline = "observed_screenlines.csv"
observed_NTD = "observed_ntd.csv"
muni_name_match = "muni_line_name_match.csv"
station_node_match = "station_node_match.csv"

# Output
[bart]
model_BART = "model_BART.csv"
model_BART_county = "model_BART_county.csv"
model_BART_Screenline = "model_BART_Screenline.csv"
obs_BART_station_md = "obs_BART_station.md"
obs_BART_county_md = "obs_BART_county.md"
BART_br = "BART_br.csv"
BART_br_am = "BART_br_am.csv"
BART_br_pm = "BART_br_pm.csv"
BART_at = "BART_at.csv"
BART_at_am = "BART_at_am.csv"
BART_at_pm = "BART_at_pm.csv"
BART_boarding_allday_csv = "BART_boarding_allday.csv"
BART_at_allday_csv = "BART_at_allday.csv"
BART_br_map = "BART_br_map.shp"
BART_br_map_am = "BART_br_map_am.shp"
BART_br_map_pm = "BART_br_map_pm.shp"
BART_at_map = "BART_at_map.shp"
BART_at_map_am = "BART_at_map_am.shp"
BART_at_map_pm = "BART_at_map_pm.shp"
county_br_day_csv = "county_br_day.csv"
county_br_am_csv = "county_br_am.csv"
county_br_pm_csv = "county_br_pm.csv"
county_at_day_csv = "county_at_day.csv"
county_at_am_csv = "county_at_am.csv"
county_at_pm_csv = "county_at_pm.csv"
BART_boarding_allday_md = "BART_boarding_allday.md"
BART_boarding_am_md = "BART_boarding_am.md"
BART_boarding_pm_md = "BART_boarding_pm.md"
BART_at_allday_md = "BART_at_allday.md"
BART_at_am_md = "BART_at_am.md"
BART_at_pm_md = "BART_at_pm.md"
county_br_day_md = "county_br_day.md"
county_br_am_md = "county_br_am.md"
county_br_pm_md = "county_br_pm.md"
county_at_day_md = "county_at_day.md"
county_at_am_md = "county_at_am.md"
county_at_pm_md = "county_at_pm.md"

[muni]
model_MUNI_Line = "model_MUNI_Line.csv"
obs_MUNI_line_md = "obs_MUNI_line.md"
MUNI_OB = "MUNI_OB.csv"
MUNI_IB = "MUNI_IB.csv"
MUNI_map_IB = "MUNI_map_IB.csv"
MUNI_map_OB = "MUNI_map_OB.csv"
MUNI_mode = "MUNI_mode.csv"
MUNI_mode_am = "MUNI_mode_am.csv"
MUNI_mode_pm = "MUNI_mode_pm.csv"
MUNI_tod = "MUNI_tod.csv"
MUNI_EB = "MUNI_EB.csv"
MUNI_LB = "MUNI_LB.csv"
MUNI_Rail = "MUNI_Rail.csv"
muni_ib_shp = "muni_ib.shp"
muni_ob_shp = "muni_ob.shp"
MUNI_ib_day = "MUNI_ib_day.md"
MUNI_ob_day = "MUNI_ob_day.md"
MUNI_ib_am = "MUNI_ib_am.md"
MUNI_ib_pm = "MUNI_ib_pm.md"
MUNI_ob_am = "MUNI_ob_am.md"
MUNI_ob_pm = "MUNI_ob_pm.md"
MUNI_mode_day = "MUNI_mode_day.md"
MUNI_mode_am_md = "MUNI_mode_am.md"
MUNI_mode_pm_md = "MUNI_mode_pm.md"
MUNI_tod_md = "MUNI_tod.md"
MUNI_EB_md = "MUNI_EB.md"
MUNI_LB_md = "MUNI_LB.md"
MUNI_Rail_md = "MUNI_Rail.md"

[screenline]
SamTrans = [ [ 40029, 7732, 52774, 33539, 51113, 21584, 50995,], [ 52118, 52264, 21493, 33737, 22464, 21522, 20306,], [ "SamTrans", "Countyline", "SamTrans", "Local Bus",],]
GG_Transit = [ [ 8318, 8315,], [ 8338, 8339,], [ "Golden Gate Transit", "Golden Gate", "Golden Gate Transit", "Local Bus",],]
GG_Ferry = [ [ 15503, 15608, 15503, 15608, 15502,], [ 15501, 15600, 15601, 15601, 15600,], [ "Ferry", "Golden Gate", "Golden Gate Ferry", "Ferry",],]
CalTrain = [ [ 14659, 14659, 14661, 14660, 14661, 14660,], [ 14658, 14655, 14655, 14655, 14656, 14656,], [ "Caltrain", "Countyline", "CalTrain", "Premium",],]
AC_transit = [ [ 52833, 52832,], [ 52495, 52494,], [ "AC Transit", "Transbay", "AC Transit", "Premium",],]
transbay_node_in = 16510
transbay_node_out = 16511
countyline_node_in = 16519
countyline_node_out = 16518
model_Screenline = "model_Screenline.csv"
obs_Screenlines_md = "obs_Screenlines.md"
obs_BART_Screenline_md = "obs_BART_Screenline.md"
transbay_BART_IB_csv = "transbay_BART_IB.csv"
transbay_BART_OB_csv = "transbay_BART_OB.csv"
Countyline_BART_IB_csv = "Countyline_BART_IB.csv"
Countyline_BART_OB_csv = "Countyline_BART_OB.csv"
Intra_SF_BART_IB_csv = "Intra_SF_BART_IB.csv"
Intra_SF_BART_OB_csv = "Intra_SF_BART_OB.csv"
transbay_AC_IB_csv = "transbay_AC_IB.csv"
transbay_AC_OB_csv = "transbay_AC_OB.csv"
transbay_overall_IB_csv = "transbay_overall_IB.csv"
transbay_overall_OB_csv = "transbay_overall_OB.csv"
Countyline_CalTrain_IB_csv = "Countyline_CalTrain_IB.csv"
Countyline_CalTrain_OB_csv = "Countyline_CalTrain_OB.csv"
Countyline_SamTrans_IB_csv = "Countyline_SamTrans_IB.csv"
Countyline_SamTrans_OB_csv = "Countyline_SamTrans_OB.csv"
Countyline_overall_IB_csv = "Countyline_overall_IB.csv"
Countyline_overall_OB_csv = "Countyline_overall_OB.csv"
GG_Transit_IB_csv = "GG_Transit_IB.csv"
GG_Transit_OB_csv = "GG_Transit_OB.csv"
GG_Ferry_IB_csv = "GG_Ferry_IB.csv"
GG_Ferry_OB_csv = "GG_Ferry_OB.csv"
GG_overall_IB_csv = "GG_overall_IB.csv"
GG_overall_OB_csv = "GG_overall_OB.csv"
screenline_overall_ib_csv = "screenline_overall_ib.csv"
screenline_overall_ob_csv = "screenline_overall_ob.csv"
screenline_overall_ib_md = "screenline_overall_ib.md"
screenline_overall_ob_md = "screenline_overall_ob.md"
transbay_BART_IB_md = "transbay_BART_IB.md"
transbay_BART_OB_md = "transbay_BART_OB.md"
Countyline_BART_OB_md = "Countyline_BART_OB.md"
Countyline_BART_IB_md = "Countyline_BART_IB.md"
SF_out_md = "SF_out.md"
SF_in_md = "SF_in.md"
transbay_AC_IB_md = "transbay_AC_IB.md"
transbay_AC_OB_md = "transbay_AC_OB.md"
transbay_overall_IB_md = "transbay_overall_IB.md"
transbay_overall_OB_md = "transbay_overall_OB.md"
Countyline_CalTrain_IB_md = "Countyline_CalTrain_IB.md"
Countyline_CalTrain_OB_md = "Countyline_CalTrain_OB.md"
Countyline_SamTrans_IB_md = "Countyline_SamTrans_IB.md"
Countyline_SamTrans_OB_md = "Countyline_SamTrans_OB.md"
Countyline_overall_IB_md = "Countyline_overall_IB.md"
Countyline_overall_OB_md = "Countyline_overall_OB.md"
GG_Transit_IB_md = "GG_Transit_IB.md"
GG_Transit_OB_md = "GG_Transit_OB.md"
GG_Ferry_IB_md = "GG_Ferry_IB.md"
GG_Ferry_OB_md = "GG_Ferry_OB.md"
GG_overall_IB_md = "GG_overall_IB.md"
GG_overall_OB_md = "GG_overall_OB.md"
transbay_node = [16510, 16511]
countyline_node = [16519, 16518]

[total]
obs_NTD_md = "obs_NTD.md"
valTotal_Operator = "valTotal_Operator.csv"
valTotal_Submode = "valTotal_Submode.csv"
valTotal_Service = "valTotal_Service.csv"
valTotal_Operator_md = "valTotal_Operator.md"
valTotal_Submode_md = "valTotal_Submode.md"
valTotal_Service_md = "valTotal_Service.md"